name: Snapshot Build Actions
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - .github/**
      - .gitignore
      - README.md
      - docs/**

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  service_build:
    name: Build Snapshot Artifact
    uses: bayer-int/calantic-github-workflows/.github/workflows/java-service-snapshot.yml@main
    secrets: inherit
    with:
      is_service: true
      runner_type: external-k8s-large-v2
